### ISSUE TITLE
Count CCN for 5 complex functions

### ISSUE THREAD

**Issue by andersblomqvist** [DD2480-Group1/mockito#2]
Count the [CCN](https://en.wikipedia.org/wiki/Cyclomatic_complexity) for these 5 complex functions by hand and also through the `lizard` tool.

* `InlineDelegateByteBuddyMockMaker` in `InlineDelegateByteBuddyMockMaker.java`
* `mockClass` in `SubclassBytecodeGenerator.java`
* `append` in `EqualsBuilder.java`
* `matches` in `ArrayEquals.java`
* `returnValueFor` in `ReturnsEmptyValues.java`

Additionally, answer the 5 questions under the Complexity header in the report.

**Comment by hanstig** [comment]
I'll evaluate the ``append`` method!

**Comment by andersblomqvist** [comment]
I will take `matches` function

**Comment by JXNCTED** [comment]
I will get `mockClass` then

**Comment by real-darth** [comment]
I will take `returnValueFor` function

**Comment by hanstig** [comment]
The ``append`` method that I was looking at turned out to be a third party method from apachecommons. It also had 100 branch coverage already. Because of this Ill switch to the equals method in ``java.org.mockito.internal.incovation.SerializableMethod.java``
